<?xml version="1.0"?>
<robot name="macros" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="box_inertia" params="x y z m">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m/12 * (z*z + x*x)}" ixy="0" ixz="0"
                             iyy="${m/12 * (y*y + x*x)}" iyz="0"
                                     izz="${m/12 * (x*x + z*z)}" 
            />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="r h m">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m/12 * (3*r*r + h*h)}" ixy="0" ixz="0"
                             iyy="${m/12 * (3*r*r + h*h)}" iyz="0"
                                    izz="${(m*r*r)/2}" 
            />
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_link" params="name x y z m">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${x} ${y} ${z}"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <box size="${x} ${y} ${z}"/>
                </geometry>
            </collision>
            <xacro:box_inertia x="${x}" y="${y}" z="${z}" m="${m}"/>
        </link>
    </xacro:macro>

    <xacro:macro name="wheel" params="name diameter thickness">
        <link name="${name}">
            <visual>
                <origin rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${thickness}" radius="${diameter/2}"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${thickness}" radius="${diameter/2}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia r="${diameter/2}" h="${thickness}" m="${WHEEL_MASS}"/>
        </link>
    </xacro:macro>

    <xacro:macro name="attach_wheel" params="wheel parent *origin">
        <joint name="${wheel}_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="${wheel}"/>
            <axis xyz="0 1 0"/>
            <xacro:insert_block name="origin"/>
        </joint>

        <transmission name="${wheel}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${wheel}_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${wheel}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <xacro:macro name="laser" params="name size mass">
      <xacro:box_link name="${name}" x="${size}" y="${size}" z="${size}" m="${mass}"/>
	  <gazebo reference="${name}">
		<sensor type="ray" name="${name}_sensor">
		  <pose>0 0 0 0 0 0</pose>
		  <visualize>true</visualize>
		  <update_rate>40</update_rate>
		  <ray>
			<scan>
			  <horizontal>
				<samples>720</samples>
				<resolution>1</resolution>
				<min_angle>-2.36</min_angle>
				<max_angle>2.36</max_angle>
			  </horizontal>
			</scan>
			<range>
			  <min>0.10</min>
			  <max>30.0</max>
			  <resolution>0.01</resolution>
			</range>
			<noise>
			  <type>gaussian</type>
			  <mean>0.0</mean>
			  <stddev>0.01</stddev>
			</noise>
		  </ray>
		  <plugin name="gazebo_ros_${name}_sensor_controller" filename="libgazebo_ros_laser.so">
			<topicName>/scan</topicName>
			<frameName>${name}</frameName>
		  </plugin>
		</sensor>
	  </gazebo>
	</xacro:macro>

</robot>

